"""Initial migration

Revision ID: 2d650bdc8319
Revises: 
Create Date: 2024-12-19 01:31:23.115855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d650bdc8319'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('AccountID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('AccountID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('notes',
    sa.Column('NoteID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AccountID', sa.Integer(), nullable=True),
    sa.Column('CreationDate', sa.DateTime(), nullable=True),
    sa.Column('Text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['AccountID'], ['account.AccountID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('NoteID')
    )
    op.create_table('results',
    sa.Column('ResultID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AccountID', sa.Integer(), nullable=True),
    sa.Column('AnalysisDate', sa.DateTime(), nullable=True),
    sa.Column('StressLevel', sa.Integer(), nullable=False),
    sa.Column('EmotionalState', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['AccountID'], ['account.AccountID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ResultID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('notes')
    op.drop_table('account')
    # ### end Alembic commands ###
